# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python35:
      python.version: '3.5'
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: sudo apt-get update
  displayName: 'Update Repos'

- script: sudo apt-get install openjdk-8-jre icedtea-8-plugin
  displayName: 'Install OpenJDK8'

- script: pip install -r Tests/requirements_test.txt
  displayName: 'Install Python Libaries'

- script: python -m pytest --color=yes -s -x -vv --cov-report term-missing --cov=pandas_bokeh Tests/
  displayName: 'Run Pytest'
