# Publish documentation on Github Pages

name: Documentation
on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-sphinx
        pip install pandas bokeh
        pip install .
    - name: Create documentation
      run: |
        git config --global user.email "patrik.hlobil@gmail.com"
        git config --global user.name "Patrik Hlobil"
        git fetch
        bash docs/sphinx/build_docs.sh
        git checkout gh-pages
        mv docs/sphinx/build/html/ html/
        rm -rf docs
        mv html docs
        git add . 
        git commit -m "Update documentation for '${GITHUB_SHA}'"
        git push
